### ISSUE TITLE
Building into single .js

### ISSUE THREAD

**Issue by AJamesPhillips** [pleerock/class-validator#1]
I'm having trouble building the `build/package` *.js files into a single .js file.  I have cloned the repo, ran `npm install`, `tsd install`, `gulp compile` and `gulp packageFiles` in it's root and it compiled perfectly.

What's the best entry point for the package, is it `decorators/Validator.js`?  I'm still trying to get my head around compiling, concatenating and minifying typescript projects and their dependancies so apologies for the novice question.  How do you use this in production?  I have the following in a model file:

    import {Validator} from "validator.ts/Validator";
    import {NotEmpty, IsInt} from "validator.ts/decorator/Validation";

And great work on the project by the way, thanks very much for sharing it.  I'm really looking forward to putting it to use.

**Comment by PLEEROCK** [comment]
Thanks,
Why are you trying to to create a single .js file? Its not supposed to work this way, e.g. there is not entry point of the package and not need of it. Simply import classes/decorators in your model as you wrote:

```typescript
import {Validator} from "validator.ts/Validator";
import {NotEmpty, IsInt} from "validator.ts/decorator/Validation";
```

You should not pack anything into a single file. What you need is to run `npm install validator.ts`, `tsd link` and simply use this package. Did you look into [samples](https://github.com/PLEEROCK/validator.ts/tree/master/sample) ?

**Comment by amcdnl** [comment]
Side note: I think the `.ts` prefix is a bad idea. It might try to look for this as a actual script instead of a module.

**Comment by PLEEROCK** [comment]
@amcdnl its kinda similar to ".js" prefixes in javascript world. there are thousands of libraries with .js prefix, thats why I choose ts prefix. But I also don't like a lot such name. But its hard to come up with a good name, especially when most of names already busy on npm. But I think we can open a new issue with new naming suggestions

**Comment by amcdnl** [comment]
I have no problem with the name, its just having it called `validator.ts` feels like a file in my project vs a npm module.

**Comment by pleerock** [comment]
package name changed.
