### ISSUE TITLE
validate positive numbers

### ISSUE THREAD

**Issue by andruhon** [pleerock/class-validator#10]
There's related issue in validator.js: https://github.com/chriso/validator.js/issues/311

They recommend to do
```JavaScript
validator.isInt(number) && number > 0
```

The question is how quickly to do that with annotations without creating custom ValidatorConstraint?

**Comment by pleerock** [comment]
Cant you use IntOptions? 

`isInt(val: number, options?: IsIntOptions)`

```typescript
export interface IsIntOptions {
    min?: number;
    max?: number;
}
```

like this:

`@IsInt({ min: 0 })`

**Comment by andruhon** [comment]
The problem is that `min` of `IsInt` and `IsFloat` is inclusive, and it is often necessary to validate that number is positive and **greater than zero**.

**Comment by pleerock** [comment]
hmm but what about `@IsInt({ min: 1 })` ? Isnt it satisfying your condition?

**Comment by andruhon** [comment]
Will work for `IsInt`, but not for `IsFloat`

**Comment by pleerock** [comment]
added `@IsPositiveFloat`, `@IsNegativeFloat`, `@IsPositiveInt`, `@IsNegativeInt` decorators, try them

**Comment by andruhon** [comment]
Works as expected. Thank you!
