### ISSUE TITLE
IsOptional Typescript dialect

### ISSUE THREAD

**Issue by thevtm** [pleerock/class-validator#101]
In Typescript the *optional* word is used to mean that an property in the object can be `undefined`.

> Optional Properties
> Not all properties of an interface may be required. Some exist under certain conditions or may not be there at all. These optional properties are popular when creating patterns like “option bags” where you pass an object to a function that only has a couple of properties filled in.

[From the Typescript hand book](https://www.typescriptlang.org/docs/handbook/interfaces.html)

But the `IsOptional` decorator checks if its an empty `string` and not `null`.
```typescript
return object[propertyName] !== "" && object[propertyName] !== null;
```
[Source](https://github.com/pleerock/class-validator/blob/6aec9968eb8fc1677e82eafd8b78fdb18e803824/src/decorator/decorators.ts#L205)

In my opinion `IsOptional` should check if it is `undefined` (and maybe `null`) and the current version should be renamed.

**Comment by rcodonnell** [comment]
@pleerock I opened a PR to address this issue. 
https://github.com/pleerock/class-validator/pull/102
