### ISSUE TITLE
create class validator to throw error,  if additional properties are present

### ISSUE THREAD

**Issue by adnan-kamili** [pleerock/class-validator#105]
I want to throw validation error if any extra properties are in the class, so validation decorator will be used on the class. But it doesn't allow creating class validation decorator. It gives following validation error:

`Unable to resolve signature of class decorator when called as an expression.`

https://github.com/pleerock/routing-controllers/issues/200

**Comment by jerradpatch** [comment]
Why not define the property in the class an check to make sure its undefinded?

**Comment by adnan-kamili** [comment]
Please check out the discussion in the following thread: https://github.com/pleerock/routing-controllers/issues/200
