### ISSUE TITLE
@IsOptional decorator not ignoring in case property is missing

### ISSUE THREAD

**Issue by adnan-kamili** [pleerock/class-validator#107]
If property is explicitly set to `null` or `""` then only `@IsOptional()` works. But if the property is missing `undefined` validations are applied, why is not `undefined` also treated in a similar manner.  I need to ignore validations on few properties in the class if they are not present, how can I do that?

**Comment by NoNameProvided** [comment]
Duplicate of #101, there is also a pending PR for this at https://github.com/pleerock/class-validator/pull/102
