### ISSUE TITLE
Async validators & model passing

### ISSUE THREAD

**Issue by zakhenry** [pleerock/class-validator#12]
Currently the signature for validator interface is 
```ts
export interface ValidatorInterface {
    validate(value: any): boolean;
}
```

This is fine for trivial validation, but more complex validation needs to be able to access the whole object, and also return promised booleans for async.

Proposed signature
```ts
export interface ValidatorInterface {
    validate(value: any, meta:ValidationMetadata): boolean | Promise<boolean>;
}
```

This will allow for 
* context-aware validators like `@IsLongerThan('propertyName')`, `@RequiredIf('propertyName', 'value')`
* async validators like `@UsernameAvailable`

Notes:
* If `skipMissingProperties == true` then a context aware validator will fail. The passed `ValidationMetadata` should pass the `skipMissingProperties` value through so that the validator can act appropriately.
* Allowing promised validation will require a *significant* refactor to [the Validator.validate method](https://github.com/pleerock/class-validator/blob/3b7b6170a0c714fc24c23438f4610e7c72225e2c/src/Validator.ts#L38-92)
 * It's probably best to refactor everything to be promise based - wrapping all calls with `Promise.resolve()` will allow both promised and basic validators to run
 * validateOrThrow would need a `timeout(() => throw new ValidationError())` in the promise chain so the thrown errors escape. (for backwards compatibility).
 * validate would need a call signature of `validate(object: any, validatorOptions?: ValidatorOptions): Promise<ValidationErrorInterface[]>`. This would have to be a breaking change.

**Comment by pleerock** [comment]
I like this idea, and think it should be here in class validator. However I need to change validator interface - all methods will be async then. It will be a breaking change.
I was planning to completely refactor class validator a while ago, but didn't had time for this. Now its look like time has come. There is one big issue in class validator right now - since it uses validator.js and mostly usable in string validations. This is annoying and not usable, and I'm planning to either switch validation framework, either add another one. I'll plan to refactor it on the next week, and will notify what other changes Im going to do. Until that provide as much proposals as you think I should include in the library.

**Comment by pleerock** [comment]
`validate(value: any, meta:ValidationMetadata): boolean | Promise<boolean>;`
I didn't get why do you need `meta:ValidationMetadata` here?

**Comment by zakhenry** [comment]
Mostly just for access to the whole entity being validated, if just that is available, that would be fine. I haven't thought too much on what makes sense

**Comment by pleerock** [comment]
I'm working on it right now, and don't think there is a need in ValidationMetadata here. If you want to access the whole entity being validated, this make sense, if you want to make a *context-aware validators like @IsLongerThan('propertyName')*. So, maybe I can send this entity and method singnature  will look like:
```validate(value: any, validatedObject: any): boolean | Promise<boolean>;```
But if you think that something else is required, let me know

**Comment by zakhenry** [comment]
Yep agreed on the signature - on looking at the `ValidationMetadata` interface again I can't think of any scenarios that that extra information would useful.

**Comment by zakhenry** [comment]
Yea, the main reason I think the `ValidationMetadata` needs to be passed is to gain access to the extra arguments passed to the validator. Example `IsLongerThan`:
### definition:

```ts
import {ValidatorConstraint, ValidatorInterface, ValidationMetadata} from "class-validator";

interface IsLongerThanMetadata extends ValidationMetadata {
  property: string;
}

@ValidatorConstraint()
export class IsLongerThan implements ValidatorInterface {

    validate(text: string, metadata: IsLongerThanMetadata): boolean {
        return metadata.object[metadata.property].length > text.length;
    }

}
```
### implementation:
```ts
import {Validate} from "class-validator";
import {IsLongerThan} from "./IsLongerThan";

export class Post {
    
    title: string;

    @Validate(IsLongerThan, {
        property: "title"
    })
    description:string;

}
```

One other thought on this - given the added complexity of context-aware validators, it would be useful for a custom validator that implements the `ValidatorInterface` to be able to define it's default error message, possibly even context-aware itself ie 

```ts
@ValidatorConstraint()
export class IsLongerThan implements ValidatorInterface {

   protected message(metadata: IsLongerThanMetadata): string {
      return `The property '${metadata.property}' must be longer than '${metadata. propertyName}'`;
   }

    validate(text: string, metadata: IsLongerThanMetadata): boolean {
        return metadata.object[metadata.property].length > text.length;
    }

}
```

**Comment by pleerock** [comment]
published a new version of class validator with all required features in `npm i class-validator@beta`

**Comment by pleerock** [comment]
added in 0.4.0
