### ISSUE TITLE
Use validators with interfaces

### ISSUE THREAD

**Issue by danajeremy** [pleerock/class-validator#126]
I'm having a simple interface like this one to avoid creating a whole object and I'd like to add some validators to it.

`interface Value {
    name: string;
    displayName: string[];
}`

Is there a way to make it works?

**Comment by NoNameProvided** [comment]
No, you cant. Interfaces are compiled away, so there is no way to get typing info from them.

**Comment by danajeremy** [comment]
Alright, thanks.
