### ISSUE TITLE
Nested validation skipmissing

### ISSUE THREAD

**Issue by DominicBoettger** [pleerock/class-validator#13]
I get the error:
[Error: Only objects and arrays are supported to nested validation]

I think it happens when nesting more than one hyrachie (and having no data in some objects).

What i tried to skip this error:

class subOptions implements ValidatorOptions {
  public skipMissingProperties: boolean;
  public groups: string[];
  constructor() {
    this.skipMissingProperties = true;
  }
}
  @ValidateNested(new subOptions())
  public beforeRent: myclass;

Any ideas?

Thanks
Dominic

**Comment by DominicBoettger** [comment]
It was my fault. I had a typo in a Variable. Sorry!

**Comment by pleerock** [comment]
oh thats good, because I was thinking what can be an issue here

**Comment by DominicBoettger** [comment]
I have the error again. And i am not able to solve it by restarting the compile process...

https://github.com/molecuel/mlcl_elements/commit/8a65347d55256867eca0d828ff3bc5ae52620902

**Comment by pleerock** [comment]
mmm can you post minimal example of usage that leads to this error?

**Comment by DominicBoettger** [comment]
```
import 'reflect-metadata';
import {IsDefined, validate} from 'class-validator';

class mytest {
  @IsDefined()
  public _id: any;
}

class mytest2 extends mytest {

}

let test = new mytest2();

async function mytestfunc() {
  let errors = await validate(test, {skipMissingProperties: true})
  console.log(errors);
}

mytestfunc();

**Comment by pleerock** [comment]
looks like problem with inherited properties? I'll check it

**Comment by DominicBoettger** [comment]
Yes it seems to ignore them completely. If you don't find another solution: I wrote a Little test and this Code works ( but it uses reflect-metadata to store the Information ).

```
import 'reflect-metadata';
import {IsDefined, validate} from 'class-validator';

class mytest {
  @IsDefined()
  @Reflect.metadata('validators', [{name: 'IsInt', options: {each: true}}])
  public _id: any;
}

class mytest2 extends mytest {

}

let test = new mytest2();

console.log(Reflect.getMetadata('validators', test, '_id'));

async function mytestfunc() {
  let errors = await validate(test, {skipMissingProperties: true})
  console.log(errors);
}

mytestfunc();
```
