### ISSUE TITLE
IsOptional() does not work like intended

### ISSUE THREAD

**Issue by bjesuiter** [pleerock/class-validator#131]
# Steps to Reproduce: 
- create typescript class with one member, for example: sum 
- add **IsOptional()** decorator and **IsInt()** decorator. 
- validate this object with sum = undefined

# Expected output: 
Validation should pass. 
Documentation for IsOptional() states: 

> Checks if given value is empty (=== null, === undefined) and if so, ignores all the validators on > the property.

# Actual output:
Validation trows because sum is undefined and undefined is not a valid integer. 
This means, the **IsInt()** decorator is executed regardless of the IsOptional flag.

**Comment by vkurlyan** [comment]
Seems, it's fixed in "class-validator": "0.7.3"

**Comment by bjesuiter** [comment]
Yes, it works now :) 
I'll close this issue.
