### ISSUE TITLE
Improvement: isRequired

### ISSUE THREAD

**Issue by DominicBoettger** [pleerock/class-validator#15]
It would be helpful to have a isRequired decorator for some stuff.

In the meantime i will solve this with a custom validator

**Comment by pleerock** [comment]
wouldn't `@NotEmpty` decorator work?

**Comment by DominicBoettger** [comment]
I am using skipmissingproperties and want to ensure that if a attribute is set, but not required will be validated and some attributes should be required and for example type of string.
I realized that if skipmissingproperties is set the validators are not executed at all. So also a NotEmpty will not work.... Do you have a solution for this kind of issue?

I need this to ensure that only validated data is saved in my database.

**Comment by pleerock** [comment]
> I realized that if skipmissingproperties is set the validators are not executed at all.

if skipmissingproperties is set then validation are not being executed only on missing properties

So, you want to use skipmissingproperties, but at same time if some property is missing, but its totally required, you want skipmissingproperties to be ignore that that property. Do I get you right?

**Comment by DominicBoettger** [comment]
@pleerock

**Comment by pleerock** [comment]
okay, got you. I'll think how do add option to decorators, so it will possible and let you know

**Comment by DominicBoettger** [comment]
Okay, thank you very much. That sounds great!

**Comment by pleerock** [comment]
I think I can do `NotEmpty` decorator the only decorator that will ignore `skipmissingproperties` option. I don't see any benefit of doing it for any other decorator, and I don't see any benifit of ignoring NotEmpty in the cases when skipmissingproperties is set to true

**Comment by DominicBoettger** [comment]
That would be great!

I am implementing a ODM layer and i have fields which are required and some (most) fields are not required.

A typical constellation will for example be @IsNotEmpty @IsInt.

To ensure that its not empty and if filled it should be a integer. 

I am pretty sure it only makes sense for IsNotEmpty.

**Comment by pleerock** [comment]
I changed my mind and decided to introduce a new decorator, as you originally suggested, but I named it `@IsDefined()`. This will be available in upcoming release soon https://github.com/pleerock/class-validator/pull/14/commits/d25ce59ae5f8b80e6559536d6bff8338436b7044

**Comment by pleerock** [comment]
added it in new version, you can try it by `npm i class-validator@beta`

**Comment by DominicBoettger** [comment]
Wow. Thanks for this great new feature. Class-validator will be a huge part of my upcoming mongodb elasticsearch ORM - layer.

**Comment by pleerock** [comment]
thats great!

**Comment by pleerock** [comment]
fixed in 0.4.0
