### ISSUE TITLE
Property 'matches' does not exist on type 'typeof Validator'.

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/class-validator#16]
I have the following snippets

```typescript
import {Validator} from 'class-validator/Validator'

console.log(Validator.matches('Tom', '[a-z]+', 'i'))
```

However, I keep getting the following error:

Property 'matches' does not exist on type 'typeof Validator'.

I am uncertain what is causing this. It seems simple enough.

Thanks

**Comment by pleerock** [comment]
`Validator` is a class here, not instance. To use instance you have two options:

```typescript
import Validator from "class-validator";
console.log(Validator.matches('Tom', '[a-z]+', 'i'))
```
or

```typescript
import {Validator} from 'class-validator/Validator'
const validator = new Validator();
console.log(Validator.matches('Tom', '[a-z]+', 'i'));
```

**Comment by st-clair-clarke** [comment]
The first option does NOT work. I did try that one.  However, the second works after changing the class Validator to the instance validator in the log statement..

**Comment by pleerock** [comment]
yeah sorry it was my typo, for surly you need to use instance

**Comment by st-clair-clarke** [comment]
Why doesn't the first option works?

**Comment by pleerock** [comment]
This option is the only option that should be used:
```typescript
import {Validator} from 'class-validator';
const validator = new Validator();
console.log(validator.matches('Tom', '[a-z]+', 'i'));
```
This works and does not need anything else. If you are using service container, you can also use Validator with it if you want

**Comment by pleerock** [comment]
any further comments?

**Comment by pleerock** [comment]
let me know if you have issues about it. Btw today I released a new version that have lot of features, including those you have asked in email

**Comment by welljs** [comment]
how to use matches in validationSchema?
