### ISSUE TITLE
IsInt validator syntax

### ISSUE THREAD

**Issue by DominicBoettger** [pleerock/class-validator#18]
The syntax has changed but i did not figure out how i could assign this without getting an error like this:
error TS2346: Supplied parameters do not match any signature of call target.

```
@IsInt({ min: 0, max: 20 }, { each: true })
public q4h: Number[];
```

I get also errors with

```
@IsInt({ min: 0, max: 20 }
```

**Comment by pleerock** [comment]
yes thats right
