### ISSUE TITLE
http://localhost:4200/validator 404 (Not Found)

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/class-validator#21]
I have the following

```typescript
import {
  IsNotEmpty,
  Matches,
  MinLength
} from "class-validator";

export class Language {
  @IsNotEmpty({
    message: 'Cannot be empty'
  })
  @MinLength(2, {
    message: "Minimum characters arg[0]"
  })
  first: string = ''

  second: string = ''
}
```

Running my angular-cli application always throws the console error

zone.js:101 GET http://localhost:4200/validator 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM5846:3fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1734(anonymous function) @ system.src.js:2759(anonymous function) @ system.src.js:3333(anonymous function) @ system.src.js:3600(anonymous function) @ system.src.js:3985(anonymous function) @ system.src.js:4448(anonymous function) @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/validator
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/validator as "validator" from http://localhost:4200/vendor/class-validator/validation/Validator.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/validator(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/validator(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:101 GET http://localhost:4200/validator 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM5846:3fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1734(anonymous function) @ system.src.js:2759(anonymous function) @ system.src.js:3333(anonymous function) @ system.src.js:3600(anonymous function) @ system.src.js:3985(anonymous function) @ system.src.js:4448(anonymous function) @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

This is the only place in my small app that I am importing 'class-validator'.
Removing the import the cosole error goes away and the application is displayed.

When I comment the annotations as shown below - the console errors disappear:

```typescript
import {
  IsNotEmpty,
  Matches,
  MinLength
} from "class-validator";

export class Language {
  // @IsNotEmpty({
  //   message: 'Cannot be empty'
  // })
  // @MinLength(2, {
  //     message: "Minimum characters arg[0]"
  //   })
  // @Matches(nounRegex, {
  //   message: 'Only letters, space, - and \' allowed'
  // })
  first: string = ''

  // @Matches(nounRegexOptional, {
  //   message: 'Only letters, space, - and \' allowed'
  // })
  second: string = ''
}
```

So it appears that the annotations are causing this issue.

Hope you can help.

**Comment by pleerock** [comment]
you need to configure your system.js and add mappings to validator and all its dependencies

**Comment by st-clair-clarke** [comment]
### angular-cli-build.js
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

```js
module.exports = function (defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
            'systemjs/dist/system-polyfills.js',
            'systemjs/dist/system.src.js',
            'zone.js/dist/**/*.+(js|js.map)',
            'es6-shim/es6-shim.js',
            'reflect-metadata/**/*.+(ts|js|js.map)',
            'rxjs/**/*.+(js|js.map)',
            '@angular/**/*.+(js|js.map)',
            '@angular2-material/**/*.js',
            'class-sanitizer/**/*',
            'class-validator/**/*',
            'configuration-manager/**/*',
            'constructor-utils/**/*',
            'event-dispatch/**/*',
            'gulpclass/**/*',
            'immutable/**/*.js',
            'lodash/**/*',
            'typedi/**/*',
        ]
  });
};

```

### system-config.js (relevant parts)

```js
var map = {
  '@angular2-material': 'vendor/@angular2-material',
  'class-sanitizer': 'vendor/class-sanitizer',
  'class-validator': 'vendor/class-validator',
  'configuration-manager': 'vendor/configuration-manager',
  'constructor-utils': 'vendor/constructor-utils',
  'event-dispatch': 'vendor/event-dispatch',
  'gulpclass': 'vendor/gulpclass',
  'immutable': 'vendor/immutable',
  'lodash': 'vendor/lodash',
  'typedi': 'vendor/typedi',
};

var packages = {
...
  'class-validator': {
    // format: 'cjs',
    'defaultExtension': 'js',
    'main': 'index.js'
  },
}
```

Hoping you can see something wrong with my code above. Thanks.

**Comment by pleerock** [comment]
class-validator depends on `validator`, try to put config to it too:

```typescript
var map = {
  '@angular2-material': 'vendor/@angular2-material',
  'class-sanitizer': 'vendor/class-sanitizer',
  'class-validator': 'vendor/class-validator',
  'validator': 'vendor/validator',
  'configuration-manager': 'vendor/configuration-manager',
  'constructor-utils': 'vendor/constructor-utils',
  'event-dispatch': 'vendor/event-dispatch',
  'gulpclass': 'vendor/gulpclass',
  'immutable': 'vendor/immutable',
  'lodash': 'vendor/lodash',
  'typedi': 'vendor/typedi',
};

var packages = {
...
  'class-validator': {
    // format: 'cjs',
    'defaultExtension': 'js',
    'main': 'index.js'
  },
  'validator': {
    'defaultExtension': 'js',
    'main': 'index.js'
  },
}
```

**Comment by pleerock** [comment]
is it fixed for you now?

**Comment by st-clair-clarke** [comment]
I am getting the same errors even with the attempted correction you suggested.

**Comment by st-clair-clarke** [comment]
It is not fixed - same problems as started.

**Comment by st-clair-clarke** [comment]
The problem was solved by the following

  'validator': {
    'defaultExtension': 'js',
    'main': 'validator.js'
  },

**Comment by st-clair-clarke** [comment]
Closing issue.
