### ISSUE TITLE
Please provide typings

### ISSUE THREAD

**Issue by alvipeo** [pleerock/class-validator#3]
With typings https://github.com/typings/typings.
Thanks!

**Comment by PLEEROCK** [comment]
I think you can expect it soon in upcoming version

**Comment by amcdnl** [comment]
+1

**Comment by PLEEROCK** [comment]
I have started to integrate typings instead of tsd, however faced some issues with typings. This will be done after https://github.com/typings/typings/issues/108 on typings repository will be resolved.

**Comment by dsebastien** [comment]
+1

**Comment by pleerock** [comment]
typings provided, tsd is removed
