### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by Zabi3l** [pleerock/class-validator#31]
Hello,

I'm in front of a problem when using the validate method.

I have an abstract class User with fields annotated with class-validator.

`export abstract class User {
    id: string;
    
    @MaxLength(200)
    @Matches(Regex.REGEX_MAIL)
    @IsNotEmpty()
    @IsDefined()
    email: string;

    @MaxLength(50)
    lastName: string;

    @MaxLength(50)
    firstName: string;

    lastModifiedHeader: string;
}`

And an other class Artisan which extends User.

`export class Artisan extends User {
    enterprise: string;
}`

When, in a component, I'm trying to validate an Artisan like this 

`artisan: Artisan = new Artisan();
validate(this.artisan, {skipMissingProperties: true}).then(...)`

I have no errors.

But if I move the annotated fields from User to Artisan then no problem.

So is there a way for the validate method to considerate the inheritance ?

Best regard and thank you in advance.

**Comment by christophercr** [comment]
Hi, I have implemented a new decorator to be used in a subclass which basically copies all the validation metadata from the parent class to the subclass.

I've added the test and updated the docs and release notes as well.

What do you think? Is this good enough to be released in v0.6.0?

Btw, the version in the package.json file is still 0.5.0-alpha.3 ?
