### ISSUE TITLE
Proposal: @IsArray validator

### ISSUE THREAD

**Issue by sanex3339** [pleerock/class-validator#37]
It would be nice if you add `@IsArray` validator.

For example i have following code:
```javascript
@IsString({
    each: true
})
public readonly reservedNames: string[];
```

with this rule validator will not throw an error with `string` value assigned to the `reservedNames` property.

`@IsArray` validator should check only for `array` type, no matter - empty array or not.

**Comment by pleerock** [comment]
yes strange that we still don't have it

**Comment by pleerock** [comment]
added in 0.6.1
