### ISSUE TITLE
Validate Promise API

### ISSUE THREAD

**Issue by 19majkel94** [pleerock/class-validator#40]
I like this library but the API could be better. I'm talking about this:
```typescript
validate(post).then(errors => { // errors is an array of validation errors
    if (errors.length > 0) {
        console.log("validation failed. errors: ", errors);
    } else {
        console.log("validation succeed");
    }
});
```
It would be better if the `validate()` reject promise on errors. To do that, [this line](/pleerock/class-validator/blob/master/src/validation/Validator.ts#L47) should be replaced with:
```typescript
const errors = executor.stripEmptyErrors(validationErrors);
return errors.length ? Promise.reject(errors) : Promise.resolve();
```
Then we simply work with `validate()` in async&await:
```typescript
try {
    await validate(post);
    console.log("validation succeed");
} catch (errors) {
    console.log("validation failed. errors: ", errors);
}
```
And if you don't want to handle the errors (like in `routing-controllers`), you can just simply do that and it will throw error on errors:
```typescript
await validate(post);
await postRepository.persist(post);
...
```
What do you think about this? It might be a breaking change, so you should publish this as a major version (to prevent auto update on npm install for older users) or we have to create a new name for the validate function with promise rejection behavior.

**Comment by pleerock** [comment]
actually I had almost same method before, its called `validateAndThrow`, but then I removed it because didn't want "double-behaviour". I like this async/await syntax more then array of errors. But since its too serious breaking change its better to add extra method instead. Maybe in next major version (1.0.0) we will replace validate method with new behaviour. (maybe we need to create a separate issue where we track everything we want to publish in next major version, and once we are ready and feel confident with all new changes, and be sure that there are no other breaking changes in a near feature - we'll publish a new major version)

**Comment by 19majkel94** [comment]
It can be `validateAndThrow`, thanks to ES6 desctructive import it's easy to do this:
```
import { validateAndThrow as validate } from "class-validator";
```
It's easier than creating the new function with name `validate` and exporting it in subdirectory like:
```
import { validate } from "class-validator/validation/throw";
```
> actually I had almost same method before

Can you restore it from git history or should I do the PR?

**Comment by pleerock** [comment]
> Can you restore it from git history or should I do the PR?

its easier to make same changes again. Also I don't like `validateAndThrow` name, maybe you have something better in mind?

**Comment by Salimlou** [comment]
Benabbou Salim.

**Comment by pleerock** [comment]
hi @Salimlou 😃

**Comment by Salimlou** [comment]
Haha sorry about that :)!!

Benabbou Salim.

**Comment by 19majkel94** [comment]
> Also I don't like validateAndThrow name, maybe you have something better in mind?

Hmmm... `restrictedValidate`? 😜 Restricted because it throw error and you have to catch them, in normal `validate` you can ignore errors or just print on console and go on without catch.

**Comment by pleerock** [comment]
nooo don't like either

**Comment by 19majkel94** [comment]
> its easier to make same changes again

Done in #42. However it volatile the DRY so it would be better to refactor the common code to private method and call it in the public API.
