### ISSUE TITLE
An error threw when ValidateNested on a missing property

### ISSUE THREAD

**Issue by Diluka** [pleerock/class-validator#51]
When the property is null or undefined, it shall return error message not throw an error

**Comment by scotthovestadt** [comment]
Yeah, I'm having this issue too. When you use `@ValidateNested` on an object and the object doesn't exist in the instance, an exception is thrown instead of returning an error.

@pleerock Would you accept a PR that fixes this issue?

**Comment by pleerock** [comment]
@scotthovestadt sure

**Comment by Cyri-L** [comment]
#59 This patch should solve this issue
