### ISSUE TITLE
I downloaded it and it doesn't work

### ISSUE THREAD

**Issue by nicolaskaco** [pleerock/class-validator#53]
Hello, I'm new to Node, I need to use this validator in a project so I tried first to make it work in an example but it just doesn't.

I downloaded every thing, I place the cmd where I downloaded the stuff and I did 'npm install', then I put an html file inside **class-validator-master\sample\sample1-simple-validation** that contains the following:

```
<html>
<head>
	<title>Clases en TS</title>
</head>
<body>
<h1>Ejemplo JS</h1>
<section id="container"></section>
<script type="text/javascript" src="app.js"></script>
</body>
</html>
```

Then I go to the browser and I get the following error in the console:

VM147 app.js:2
Uncaught ReferenceError: require is not defined(…)(anonymous function) @ VM147 app.js:2

Thank you for your time.

**Comment by jerradpatch** [comment]
App.js is that your project app? If your going to include the validator js file you should find it in the dist from the validator fold that was downloaded with npm

**Comment by pleerock** [comment]
@nicolaskaco did you figure out your issue?

**Comment by pleerock** [comment]
I guess I can close it because of no answer from author of this issue
