### ISSUE TITLE
Comparing password fields

### ISSUE THREAD

**Issue by ChrLipp** [pleerock/class-validator#54]
I am using class-validator to validate my incoming requests in an express application and I am very happy with it.

Currently I am implementing a registration service, my request has two password fields, `password` and `password2`. I would like to compare them to each other but it seems that this functionality is lacking in class-validator.

Is class-validator able to handle this scenario already or is this a feature request?

**Comment by pleerock** [comment]
Using [Custom validation classes](https://github.com/pleerock/class-validator#custom-validation-classes) and [Custom validation decorators](https://github.com/pleerock/class-validator#custom-validation-decorators) you can create a complex validations like in your case

**Comment by ChrLipp** [comment]
I had the opinion that this solutions are only suited for validation single fields, not for comparing two fields.

**Comment by pleerock** [comment]
no its totally possible to implement. Take a look on [this](https://github.com/pleerock/class-validator/tree/master/sample/sample6-custom-decorator) example it does exactly what you want - make comparasion on a different property of the same object.

**Comment by ChrLipp** [comment]
IsLongerThan looks promising, I will try that.
Thanks for your work!

Regards, Christian

**Comment by ChrLipp** [comment]
Unfortunately this code doesn't compile.

    error TS2345: Argument of type '{ constraints: string[]; options: ValidationOptions | undefined; propertyName: string; target: Fu...' is not assignable to parameter of type 'ValidationDecoratorOptions'.
      Types of property 'options' are incompatible.
        Type 'ValidationOptions | undefined' is not assignable to type 'ValidatorOptions'.
          Type 'undefined' is not assignable to type 'ValidatorOptions'.

The version of typescript is

    "typescript": "2.1.4",
