### ISSUE TITLE
@Length minimum validation off by 1

### ISSUE THREAD

**Issue by jerradpatch** [pleerock/class-validator#61]
Sorry, to give keep lodging issues, I am just using this validation lib a lot recently. 

so I have this,
```javascript
  @Length(2, 40)
  @IsString()
  BRIEF_DESCRIPTION : string =null;
```
when I enter '1' I get no validation error. When I have this 
```javascript
  @Length(2, 40)
  @IsString()
  BRIEF_DESCRIPTION : string =null;
```
and enter '1' I get an error 'BRIEF_DESCRIPTION must be longer than or equal to 2 characters'.

In addition, it seems @MinLength(min: number), has the same issue? Where a validation error isn't returned unless @MinLength(2) or greater?

using version 0.6.0

**Comment by pleerock** [comment]
fixed by #96
