### ISSUE TITLE
Integration with Routing-Controllers

### ISSUE THREAD

**Issue by awaragi** [pleerock/class-validator#65]
Hi,

Do you have some examples on how to integrate your two great frameworks? What would be the best strategy? Perhaps using Middlewares to keep everything using decorators?

Thanks for the great work!

**Comment by pleerock** [comment]
integration is pretty simple since both are completely isolated frameworks. If you are talking about syntax sugar integration, then there is a [PR](https://github.com/pleerock/routing-controllers/pull/78) that integrates class-validator into routing-controller that will be merged soon

**Comment by awaragi** [comment]
fantastic news. I am so looking forward to the next version of routing-controllers
