### ISSUE TITLE
Rename package name

### ISSUE THREAD

**Issue by pleerock** [pleerock/class-validator#7]
Looks like for some users (@amcdnl) its confusing to have a `.ts` postfix in the package name. What are suggestions for a new package name?

* validator.ts (old name)
* validator-ts
* constraint-validator
* .... ?

**Comment by amcdnl** [comment]
validator-ts is nice

**Comment by pleerock** [comment]
thanks for feedback, any better alternatives?

**Comment by pleerock** [comment]
finally renamed to `class-validator`
