### ISSUE TITLE
@IsOptional() cannot be imported

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/class-validator#90]
Hi, I cannot import @IsOptional() validator. Please varify that this is actually present.

Cheers

**Comment by NoNameProvided** [comment]
It's not released yet.

**Comment by st-clair-clarke** [comment]
Thanks. I saw it in the documentation.

**Comment by NoNameProvided** [comment]
We can ping @pleerock, to see the reasons which block?

**Comment by pleerock** [comment]
released in `0.7.1`
